name    'desalvo-cvmfs'
version '0.1.1'
source  'https://github.com/desalvo/puppet-cvmfs'
author 'desalvo'
license 'Apache License, Version 2.0'
summary 'Puppet module for CVMFS customizations'
description 'Puppet module to customize the CVMFS HTTP based filesystem'
project_page 'https://github.com/desalvo/puppet-cvmfs' 
